version: 2.1

jobs:
  build:                        # Job Name
    docker:
      -  image: cimg/node:lts   # Image for node.js app

    steps:
      - checkout
      - run:
          name: Install Node.js dependancies
          command: |
            npm install
      - run:
          name: Build App
          command: |
            npm run build
      - run:
          name: list build folder
          command: |
            ls build
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build
      
  deploy:
    docker:
      - image: amazon/aws-cli:latest
    steps:
      - checkout
      - run:
          name: Install Circleci deps on docker container
          command: |
            yup update
            yum install tar gzip 
      - attach_workspace:
          at: ~/      
      - run:
          name: Create new S3 bucket
          command: |                      #takes the first 8 characters from workflow ID and create a unique stackname & Bucket name
            aws cloudformation deploy \
              --template-file .circleci/bucket.yml  \
              --stack-name Demo-react-app-${CIRCLE_WORKFLOW_ID:0:8} \
              --parameters-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}"

      - run:
          name: Upload build folder to bucket
          command: |
            aws s3 sync build s3://demo-website-${CIRCLE_WORKFLOW_ID:0:8} --recursive

workflows:
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build