version: 2.1

jobs:
  build:
    docker:
      -  image: cimg/node:lts

    steps:
      - checkout
      - run:
        name: Build App
        command: |
          npm run build
      
      - run:
          name: list build folder
          command: |
            ls build

workflows:
  default:
    jobs:
      - build